GET http://localhost:3001/api/users/get/all http/1.1

###

POST http://localhost:3000/api/login?key=$2a$12$/gEPLKAlLnet0.lzftO7G.qhK3EA3q/e92EzyDV.QPPzREqW9RInV.mvkP9iwDms0Xxyx27pCrmoqDcLj2 http/1.1
content-type: application/json

{
"username":"Brianna",
"password":"2013"
}

###

POST http://localhost:3000/api/signup?key=$2a$12$/gEPLKAlLnet0.lzftO7G.qhK3EA3q/e92EzyDV.QPPzREqW9RInV.mvkP9iwDms0Xxyx27pCrmoqDcLj2 http/1.1
content-type: application/json

{
    "id":"8ff39508-c80b-4419-9646-0bdd5277817a",
    "username":"Brianna",
    "password":"2013",
    "blocked":false,
    "verified":true,
    "bot": false
}

###

POST http://localhost:8080/api/create-room?key=000 http/1.1
content-type: application/json

{
    "id":"123",
    "name":"Alvinsdfsafasdfsf",
   "users":["Alvin"],
   "passcode":"pp"
}

###

GET http://localhost:8080/api/get-rooms?key=000&user=Alvin http/1.1

###
POST http://localhost:8080/api/block_user?key=000 http/1.1
content-type: application/json

{
"user":"Alvin",
"blockStatus":false
}

###
POST http://localhost:3000/api/join-room?key=$2a$12$/gEPLKAlLnet0.lzftO7G.qhK3EA3q/e92EzyDV.QPPzREqW9RInV.mvkP9iwDms0Xxyx27pCrmoqDcLj2  http/1.1
content-type: application/json

{
"user":"Alvin",
"passcode":"8888",
"id": "b10ac028-f41a-49ed-a501-61347dece821"
}
###
GET http://localhost:8080/api/users/get/admin/ http/1.1

###

GET http://localhost:8080/api/users/get/admin/password1234 http/1.1

###

PUT http://localhost:8080/api/users/block http/1.1
content-type: application/json

{
    "user":"admin",
    "blockStatus":true
}

