name: Format code using prettier

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install Node.js and Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Format code
        run: npx prettier --write .
      - name: Commit changes to git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Format code (Automatic workflow commit)"
