name: Format code using prettier

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install Node.js and Prettier
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Format code
        run: npx prettier --write .
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.verify_diff.outputs.changed == 'true'
        env:
          GIT_USER: ${{ secrets.USERNAME_SECRET }}
          GIT_MAIL: ${{ secrets.MAIL_SECRET }}
        run: |
          git config  user.email "${GIT_MAIL}"
          git config  user.name "${GIT_USER}"
          git add .
          git commit -m "Commit workflow changes"
          git push
